name: Nanopi T6

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      URL:
        description: '选择源码：'
        default: 'immortalwrt'
        required: true
        type: choice
        options: [ openwrt,  immortalwrt ]

      branch:
        description: '源码的分支(immortalwrt无main)'
        default: 'openwrt-25.12'
        required: true
        type: choice
        options: [ main, master, openwrt-23.05,  openwrt-24.10 openwrt-25.12 ]
        
      config_s:
        description: '选择config配置文件'
        default: 't6.config'
        required: true
        type: choice
        options: [ r5s.config, t6.config ]
        
      target:
        description: '选择要生成的机型：'
        default: 'armv8'
        required: true
        type: choice
        options: [ armv8 ]

env:
  #REPO_URL: https://github.com/immortalwrt/immortalwrt
  #REPO_BRANCH: openwrt-24.10
 # CONFIG_FILE: configs/r5s.config
  DIY_P1_SH: diy1.sh
  DIY_P2_SH: diy2.sh
  FEEDS_CONF: feeds.conf.default
  FILES: files1
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai

jobs:
  Build:
    runs-on: ubuntu-24.04

    name: 编译${{github.event.inputs.URL}}-${{github.event.inputs.target}}
    env:
      REPO_URL: ${{github.event.inputs.URL}}
      REPO_BRANCH: ${{github.event.inputs.branch}}
      CONFIG_FILE: configs/${{github.event.inputs.config_s}}
      TARGET_DEVICE: ${{github.event.inputs.target}}

    steps:
    - name: 准备结束
      uses: actions/checkout@main

    - name: 释放磁盘空间
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
        
    - name: 安装编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo /bin/bash -c "$(curl -sL https://git.io/vokNn)"
        sudo -E apt-fast -y -qq install asciidoc bash bcc bin86 binutils bison bzip2 clang file flex g++ g++-multilib gawk gcc-multilib gettext git gzip help2man /
        intltool libbpf-dev libboost-dev libelf-dev libncurses-dev libssl-dev libthread-queue-any-perl libusb-dev libxml-parser-perl linux-tools-generic llvm /
        make patch perl-modules pkg-config python3-dev python3-pip python3-pyelftools python3-setuptools rsync sharutils swig time unzip util-linux wget xsltproc zlib1g-dev zip zstd
        sudo -E apt-fast -y -qq install dos2unix dwarves jq npm quilt
        sudo -E npm install -g pnpm
        sudo -E npm install -g n
        sudo -E n stable
        pip3 install --user -U pylibfdt --break-system-packages
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 下载源码
      working-directory: /workdir
      run: |
        # 设置编译源代码
          if [[ "${{github.event.inputs.URL}}" == *"openwrt"* ]]; then
              REPO_URL="https://github.com/openwrt/openwrt"
          elif [[ "${{github.event.inputs.URL}}" == *"immortalwrt"* ]]; then
              REPO_URL="https://github.com/immortalwrt/immortalwrt"
          else
              echo "源代码仓库的地址无法被识别或无法访问."
              exit 1
          fi
        # 克隆源代码
        git clone $REPO_URL -b ${{env.REPO_BRANCH}} openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: 加载diy.sh
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH
        
    - name: 更新、安装"feeds"
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 加载自定义配置
      run: |
        [ -e $FILES ] && mv $FILES openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    #- name: 加载scripts下的补丁
      #run: |
        #chmod +x $GITHUB_WORKSPACE/scripts/*.sh
        #cd openwrt
        #$GITHUB_WORKSPACE/scripts/03-convert_translation.sh
        #$GITHUB_WORKSPACE/scripts/preset-clash-core.sh
        #$GITHUB_WORKSPACE/scripts/v2raya-dat.sh
        #$GITHUB_WORKSPACE/scripts/passwall2.sh
    
    - name: 下载依赖
      working-directory: ./openwrt
      run: |
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: 编译固件
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build"
        make -j$(nproc) || make -j1 || make -j1 V=s
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: 整理文件
      id: organize
      run: |
        cd openwrt/bin/targets/*/*
        # 整理固件包时候,删除您不想要的固件或者文件,让它不需要上传到Actions空间
        rm -rf packages
        rm -rf feeds.buildinfo
        rm -rf version.buildinfo
        rm -rf *kernel.bin
        rm -rf profiles.json
        rm -rf *rootfs.img
        rm -rf *rootfs.tar.gz
        rm -rf *.manifest
        rm -rf sha256sums
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV

    - name: 上传固件
      uses: actions/upload-artifact@main
      with:
        name: immortalwrt${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}
